### ISSUE TITLE
連結失效和Server error統計

### ISSUE THREAD

**Issue by sp8va100** [livingbio/article-extraction-benchmark#2]
# Problem
有些連結已經失效，有些我們的parser不能爬
統整資料：https://paper.dropbox.com/doc/Benchmark-A.I.-Parser--BV6t1MdCnejWabP9W9DZoPMiAg-UPbZxMrxYm4XWR452HaTq

**Comment by sp8va100** [comment]
# Solve
記錄下不能用的連結，將`output/`和`ground-truth.json`中的那些連結去除，並重新evaluate

**Comment by lucemia** [comment]
麻煩確認一下評分標準，然後來增加 dataset
