### ISSUE TITLE
麻煩確認一下評分標準

### ISSUE THREAD

**Issue by lucemia** [livingbio/article-extraction-benchmark#4]
確認評分標準是否會有不合理的情況 

e.g. image alt 造成扣分

_Originally posted by @lucemia in https://github.com/livingbio/article-extraction-benchmark/issues/2#issuecomment-964880095_

**Comment by sp8va100** [comment]
Update評分標準和內文定義在paper中：https://paper.dropbox.com/doc/Benchmark-A.I.-Parser--BV6t1MdCnejWabP9W9DZoPMiAg-UPbZxMrxYm4XWR452HaTq

* 我們parser評分低的原因
1. 主要：會爬到文章以外的資訊
2. 我們的parser會爬到圖片的註解，但是benchmark定義中圖片的註解並不算在內文中
3. 我們的parser爬圖片的連結到內文中(數量很大)，benchmark中沒有

第三點應該造成分數嚴重下降，因為爬到的連結數量很多且連結會被拆成許多個詞，在計算上會被嚴重扣分。
因此，根據上面的原因，我們的評分應該正常來說應該會在更高。
