### ISSUE TITLE
調整評分機制

### ISSUE THREAD

**Issue by lucemia** [livingbio/article-extraction-benchmark#6]
# Problem 

調整評分機制，避免我們 Parser 爬到的正確 extra 資訊變成扣分項

# Solution
寫一個 post process 機制，將我們 Parser 回傳的結果中的多餘資訊濾掉後在計分

**Comment by sp8va100** [comment]
Update in : https://paper.dropbox.com/doc/Benchmark-A.I.-Parser--BWBUq0_rFdVI8Lj3a_rFoq~5Ag-UPbZxMrxYm4XWR452HaTq

**Comment by lucemia** [comment]
> Update in : https://paper.dropbox.com/doc/Benchmark-A.I.-Parser--BWBUq0_rFdVI8Lj3a_rFoq~5Ag-UPbZxMrxYm4XWR452HaTq

看起來剩下的 case 都可以算成是正確的扣分

**Comment by lucemia** [comment]
![image](https://user-images.githubusercontent.com/432851/141418265-fb3a1d93-c4bb-44b7-b79f-14f83279788f.png)

**Comment by lucemia** [comment]
@sp8va100 看起來可以進到 #5 用同樣的邏輯產生 dataset

**Comment by sp8va100** [comment]
所以我們需要的內容就是正文和圖片的連結就可以嗎？
